include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    avoid_print: false
    public_member_api_docs: false
