name: kiss_repository_tests
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/WAMF/kiss_repository_tests

environment:
  sdk: ^3.8.0

dependencies:
  test: ^1.24.0
  kiss_repository: ^0.11.0
  
dev_dependencies:
  very_good_analysis: ^6.0.0
