name: kiss_repository_tests
description: Tests for kiss_repository package
version: 0.2.0
repository: https://github.com/WAMF/kiss_repository_tests

environment:
  sdk: ^3.8.0

dependencies:
  test: ^1.24.0
  kiss_repository: ^0.12.0
  meta: ^1.9.0
  
dev_dependencies:
  very_good_analysis: ^6.0.0
